name: SFDX-CLI DEV Deploy from Repository
on: 
  pull_request:
    branches:
      - develop
    paths:
      - 'force-app/**'
jobs:
  SFDX-CLI-DEV-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch all history commit
          fetch-depth: 0
      - run: npm install sfdx-cli --location=global
      - run: echo 'y' | sfdx plugins:install sfdx-git-delta
      - run: sfdx force:auth:jwt:grant --clientid ${{ secrets.CLIENT_ID_DEV }} --jwtkeyfile=build/serverdev.key --username ${{ secrets.USERNAME_DEV }} --setdefaultdevhubusername --instanceurl=${{ secrets.INSTANCE_URL_DEV }} --setalias org
      - run: git fetch origin "+refs/heads/*:refs/remotes/origin/*"
      - run: sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output . -i .gitignore
      - run: sfdx force:source:deploy -x package/package.xml -u org