name: SFDX-CLI Validate from Repository
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'
jobs:
  SFDX-CLI-Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch all history commit
          fetch-depth: 0
      - run: npm install sfdx-cli --location=global
      - run: echo 'y' | sfdx plugins:install sfdx-git-delta
      - run: sfdx force:auth:jwt:grant --clientid ${{ secrets.CLIENTID_PRD }} --jwtkeyfile=build/server.key --username ${{ secrets.USERNAME_PRD }} --setdefaultdevhubusername --instanceurl=${{ secrets.INSTANCE_URL_PRD }} --setalias org
      - run: git fetch origin "+refs/heads/*:refs/remotes/origin/*"
      - run: sfdx sgd:source:delta --to "HEAD" --from $(git merge-base HEAD origin/main) --output . -i .gitignore
      - run: sfdx force:source:deploy -x package/package.xml -c -l RunLocalTests -u org