name: SFDX-CLI QA Validate from Repository
on: 
  pull_request:
    branches:
      - qa
    paths:
      - 'force-app/**'
jobs:
  SFDX-CLI-QA-Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch all history commit
          fetch-depth: 0
      - run: npm install sfdx-cli --location=global
      - run: echo 'y' | sfdx plugins:install sfdx-git-delta
      - run: sfdx force:auth:jwt:grant --clientid ${{ secrets.CLIENT_ID_QA }} --jwtkeyfile=build/serverqa.key --username ${{ secrets.USERNAME_QA }} --setdefaultdevhubusername --instanceurl=${{ secrets.INSTANCE_URL_QA }} --setalias org
      - run: git fetch origin "+refs/heads/*:refs/remotes/origin/*"
      - run: sfdx sgd:source:delta --to "HEAD" --from $(git merge-base HEAD origin/qa) --output . -i .gitignore
      - run: sfdx force:source:deploy -x package/package.xml -c -l RunLocalTests -u org